# Generated by Django 2.2.1 on 2019-05-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='uuid',
            field=models.CharField(default='f4891aee-2334-4109-abef-df0598f26465', max_length=60),
        ),
    ]
