# Generated by Django 2.2.1 on 2019-06-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='uuid',
            field=models.CharField(default='0b09ee6e-7a82-4a9b-a2ac-a2e54a979097', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='8a4caa2e-14c3-4940-8641-0f777a72bdde', max_length=60, unique=True),
        ),
    ]
