# Generated by Django 2.2.1 on 2019-05-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='uuid',
            field=models.CharField(default='37490bf1-c655-4ef1-8751-19058a2b8b1c', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='01cb9e5e-0dc4-4b5f-ad73-55c5f2fade6c', max_length=60, unique=True),
        ),
    ]
