# Generated by Django 2.2.1 on 2019-05-21 02:20

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='uuid',
            field=models.CharField(default='9f6bbcfa-3174-4cc0-92d5-3428e85ed970', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='98ef5d44-212f-43ed-89b5-ab8b7192c43b', max_length=60, unique=True),
        ),
    ]
