# Generated by Django 2.2.1 on 2019-05-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190521_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='uuid',
            field=models.CharField(default='95daf561-c11f-4443-bed1-893248969289', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='3845d45e-d669-4ce5-9a52-a2a184789d51', max_length=60, unique=True),
        ),
    ]
