# Generated by Django 2.2.1 on 2019-05-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190520_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='uuid',
            field=models.CharField(default='46364805-b9ce-457f-95c5-688c43e316ef', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='b43e0ea3-7bf0-4d7f-a66b-47d157025747', max_length=60, unique=True),
        ),
    ]
