# Generated by Django 2.2.1 on 2019-05-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190530_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='uuid',
            field=models.CharField(default='dbc38fa4-a636-4079-abe9-4a1a60ab8f08', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='fa51bc6d-b6ed-4865-95c1-804576a8a49f', max_length=60, unique=True),
        ),
    ]
