# Generated by Django 2.2.1 on 2019-05-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190521_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='uuid',
            field=models.CharField(default='ed93e191-a832-466c-a584-10327d1cad9f', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='77efbed7-1075-4b86-95b8-452bfa052f83', max_length=60, unique=True),
        ),
    ]
