# Generated by Django 2.2.1 on 2019-05-31 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190530_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='uuid',
            field=models.CharField(default='b8736677-9a77-42cc-86c6-07b1a020cf7e', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='09e38542-5d3d-41c4-8f26-616c47ad359c', max_length=60, unique=True),
        ),
    ]
