# Generated by Django 2.2.1 on 2019-06-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190530_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='uuid',
            field=models.CharField(default='0ab05829-c646-46dc-8b09-0929b0d0f576', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='4771f30f-9714-4189-8949-12af2da8e3d5', max_length=60, unique=True),
        ),
    ]
