# Generated by Django 2.2.1 on 2019-05-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190521_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='uuid',
            field=models.CharField(default='26e91c82-2d60-4523-be68-e1447202b620', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='baf5cbc9-0c38-4485-8844-127446e055d0', max_length=60, unique=True),
        ),
    ]
