# Generated by Django 2.2.1 on 2019-06-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190601_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='uuid',
            field=models.CharField(default='3507cd89-e664-4004-8e4d-e478854cfe5b', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='884d5907-8b9e-42a0-8b15-76be2d78f7db', max_length=60, unique=True),
        ),
    ]
