# Generated by Django 2.2.1 on 2019-05-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190521_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussion',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='uuid',
            field=models.CharField(default='726bce7a-bc6d-42b7-9517-487d9ad42c96', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='29b512d4-236d-4a26-826e-94abaa9a7710', max_length=60, unique=True),
        ),
    ]
