# Generated by Django 2.2.1 on 2019-05-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190525_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='uuid',
            field=models.CharField(default='8abbc243-7ab9-4653-b7fe-4f610c02df0d', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='862ba9c0-80ae-471a-bcb3-b3484021044b', max_length=60, unique=True),
        ),
    ]
