# Generated by Django 2.2.1 on 2019-05-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190530_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='uuid',
            field=models.CharField(default='bc49e6c4-745e-4ee8-b539-f1debb33dde0', max_length=60),
        ),
    ]
