# Generated by Django 2.2.1 on 2019-05-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190530_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='3c615b7d-dd09-40c9-af65-c363d4d77a17', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='uuid',
            field=models.CharField(default='a64dd4c0-6ebd-42f6-a6c6-b07f4ad7aac8', max_length=60),
        ),
    ]
