# Generated by Django 2.2.1 on 2019-06-05 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190530_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopic', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='uuid',
            field=models.CharField(default='83fb5c2f-eb45-42f3-b3d9-b16d6fcd1995', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='dcd56cff-02cf-479d-a115-fed6364439d1', max_length=60, unique=True),
        ),
    ]
