# Generated by Django 2.2.1 on 2019-06-05 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190605_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='discussion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Discussion'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='uuid',
            field=models.CharField(default='b51c9221-acda-4d99-9af9-16218af5cd7e', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='29186879-b20e-4348-a8b7-999acf8d0056', max_length=60, unique=True),
        ),
    ]
